import { Michroma } from "next/font/google";
import "./globals.css";

const michroma = Michroma({
  subsets: ["latin"],
  weight: "400", // Michroma cuma punya 1 weight
  variable: "--font-michroma",
});

export const metadata = {
  title: "Jean Samuel Putra Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 <body
        className={`${michroma.variable} antialiased bg-black text-white`}
        suppressHydrationWarning={true}
      >
        <div id="app-root">{children}</div>
      </body>
    </html>
  );
}
